markdown: rdiscount
permalink: /:title/
url: http://weihoop.com
name: Weihoop.com
author: weihoop
email: weihoop#gmail.com 
weibo: bingqihan 
github: weihoop
pygments: true
safe: true
paginate: 20
about: "这里是 weihoop 的个人博客"
